services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: poc
    ports:
      - 5430:5430
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  poc-server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: poc-server
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www
    depends_on:
      - db

volumes:
  postgres_data: {}
